In [1]:
import numpy as np

data = np.arange(12);
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
data.reshape(3,4)
# array([[ 0,  1,  2,  3],
#       [ 4,  5,  6,  7],
#       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
type(data) # numpy.ndarray

numpy.ndarray

In [5]:
data.ndim  # 数组维度的个数，输出结果：1 ，表示是一维数组

1

In [6]:
data = data.reshape(3,4)
data.ndim  # 2

2

In [7]:
data.shape  # 数组的维度，输出结果（3,4） 表示3行4列

(3, 4)

In [8]:
data.size  # 数组元素的个数，输出结果：12

12

In [9]:
data.dtype  # dtype('int32')  数组元素的类型，表示元素都是int32类型的

dtype('int32')

In [10]:
data1 = np.array([1,2,3])  # 创建一个一维数组
data1  # array([1, 2, 3])

array([1, 2, 3])

In [11]:
data2 = np.array([[1,2,3],[4,5,6]])  # 创建一个二维数组
data2
# array([[1, 2, 3],
#       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.zeros((3,4))  # 创建一个全0数组
# array([[0., 0., 0., 0.],
#       [0., 0., 0., 0.],
#       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))  # 创建全1数组
# array([[1., 1., 1., 1.],
#       [1., 1., 1., 1.],
#       [1., 1., 1., 1.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.empty((5,2)) # 创建全空数组，其实每个值都是接近于0的数
#array([[2.12199582e-314, 0.00000000e+000],
#       [1.46211862e-311, 7.90505033e-323],
#       [6.36598737e-314, 5.10318768e-310],
#       [1.16113488e-309, 1.18575755e-322],
#       [1.85676737e+294, 0.00000000e+000]])

array([[2.12199582e-314, 0.00000000e+000],
       [1.46211862e-311, 7.90505033e-323],
       [6.36598737e-314, 5.10318768e-310],
       [1.16113488e-309, 1.18575755e-322],
       [1.85676737e+294, 0.00000000e+000]])

In [15]:
np.arange(1,20,5)  # array([ 1,  6, 11, 16])  从1开始，20结束（不包含20），步长为5

array([ 1,  6, 11, 16])

In [16]:
np.array([1,2,3,4], float)  # array([1., 2., 3., 4.])

array([1., 2., 3., 4.])

In [17]:
np.ones((2,3), dtype='float64')
# array([[1., 1., 1.],
#       [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
data_one = np.array([[1,2,3],[4,5,6]])

In [19]:
data_one
# array([[1, 2, 3],
#       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 查看数据类型

data_one.dtype
# dtype('int32')

dtype('int32')

In [21]:
data_one.dtype.name
# 'int32'

'int32'

In [22]:
# 转换数据类型
data = np.array([[1,2,3],[4,5,6]])
data.dtype  # dtype('int32')

dtype('int32')

In [23]:
float_data = data.astype(np.float64)
float_data.dtype  # dtype('float64')

dtype('float64')

In [24]:
float_data
# array([[1., 2., 3.],
#       [4., 5., 6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
float_data = np.array([1.2, 2.3, 3.4,4.5,5.6])
float_data  # array([1.2, 2.3, 3.4, 4.5, 5.6])

array([1.2, 2.3, 3.4, 4.5, 5.6])

In [26]:
float_data.dtype  # dtype('float64')

dtype('float64')

In [30]:
int_data = float_data.astype(np.int64)
int_data  # array([1, 2, 3, 4, 5], dtype=int64)

array([1, 2, 3, 4, 5], dtype=int64)

In [31]:
str_data = np.array(['1', '2', '3'])
str_data  # array(['1', '2', '3'], dtype='<U1')

array(['1', '2', '3'], dtype='<U1')

In [32]:
int_data = str_data.astype(np.int64)
int_data  # array([1, 2, 3], dtype=int64)

array([1, 2, 3], dtype=int64)

In [33]:
# 数组运算
# 向量化运算

data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[1,2,3],[4,5,6]])
data1+ data2
# array([[ 2,  4,  6],
#       [ 8, 10, 12]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
data1 * data2
# array([[ 1,  4,  9],
#       [16, 25, 36]])

array([[ 1,  4,  9],
       [16, 25, 36]])

In [35]:
data1 - data2
# array([[0, 0, 0],
#       [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
data1 / data2
# array([[1., 1., 1.],
#       [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 数组的广播
# numpy 数组间的基础运算是一对一，也就是a.shape==b.shape，
# 但是当两者不一样的时候，就会自动触发广播机制，如下例子：

In [37]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape  # (4, 1)

(4, 1)

In [38]:
arr2 = np.array([1,2,3])
arr2.shape  # (3,)

(3,)

In [39]:
arr1 + arr2
# array([[1, 2, 3],
#       [2, 3, 4],
#       [3, 4, 5],
#       [4, 5, 6]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [40]:
# 数组与标量间的运算
data1 = np.array([[1,2,3],[4,5,6]])
data2 =10
data1 + data2
# array([[11, 12, 13],
#       [14, 15, 16]])

array([[11, 12, 13],
       [14, 15, 16]])

In [41]:
data1 * data2
# array([[10, 20, 30],
#       [40, 50, 60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [42]:
data1 - data2
# array([[-9, -8, -7],
#       [-6, -5, -4]])

array([[-9, -8, -7],
       [-6, -5, -4]])

In [43]:
data1 / data2
# array([[0.1, 0.2, 0.3],
#       [0.4, 0.5, 0.6]])

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [45]:
# ndarray 的索引和切片
# 整数索引和切片的基本使用
arr = np.arange(8)
arr  # array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
arr[5]  # 5

5

In [47]:
arr[3:5]  # array([3, 4])

array([3, 4])

In [48]:
arr[1:6:2]  # array([1, 3, 5])

array([1, 3, 5])

In [49]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d
# array([[1, 2, 3],
#       [4, 5, 6],
#       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[1]  # array([4, 5, 6])

array([4, 5, 6])

In [51]:
arr2d[0,1]  # 2

2

In [52]:
arr2d[:2]
# array([[1, 2, 3],
#       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2d[0:2, 0:2]
# array([[1, 2],
#       [4, 5]])

array([[1, 2],
       [4, 5]])

In [54]:
arr2d[1, :2]  # array([4, 5])

array([4, 5])

In [ ]:
# 花式（数组）索引的基本使用

In [55]:
demo_arr = np.empty((4,4))
demo_arr
# array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
#        1.24611674e-306],
#       [2.22520559e-306, 1.33511018e-306, 1.42413555e-306,
#        1.78019082e-306],
#       [1.37959740e-306, 6.23057349e-307, 1.11260483e-306,
#        8.90098127e-307],
#       [3.56034566e-307, 1.37961641e-306, 1.39071445e-307,
#        1.08223437e-312]])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24611674e-306],
       [2.22520559e-306, 1.33511018e-306, 1.42413555e-306,
        1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.11260483e-306,
        8.90098127e-307],
       [3.56034566e-307, 1.37961641e-306, 1.39071445e-307,
        1.08223437e-312]])

In [56]:
for i in range(4):
    demo_arr[i] = np.arange(i,i+4)
demo_arr
# array([[0., 1., 2., 3.],
#       [1., 2., 3., 4.],
#       [2., 3., 4., 5.],
#       [3., 4., 5., 6.]])

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [57]:
demo_arr[[0,2]]
# array([[0., 1., 2., 3.],
#       [2., 3., 4., 5.]])

array([[0., 1., 2., 3.],
       [2., 3., 4., 5.]])

In [58]:
demo_arr[[1,3],[1,2]]  # array([2., 5.])  获取索引为（1,1）（3,2）的元素

array([2., 5.])

In [59]:
demo_arr[(1,3),(1,2)]  # array([2., 5.])

array([2., 5.])

In [60]:
# 布尔型
student_name = np.array(['Tom', 'Lily', 'Jack', 'Rose'])
student_name  #  array(['Tom', 'Lily', 'Jack', 'Rose'], dtype='<U4')

array(['Tom', 'Lily', 'Jack', 'Rose'], dtype='<U4')

In [61]:
student_score = np.array([[79, 88, 80], [89, 90, 92], [83, 78, 85], [78, 76, 80]])
student_score
# array([[79, 88, 80],
#       [89, 90, 92],
#       [83, 78, 85],
#       [78, 76, 80]])

array([[79, 88, 80],
       [89, 90, 92],
       [83, 78, 85],
       [78, 76, 80]])

In [62]:
student_name == 'Jack' 
# array([False, False,  True, False])

array([False, False,  True, False])

In [64]:
student_score[student_name == 'Jack']
# array([[83, 78, 85]])

array([[83, 78, 85]])

In [65]:
student_score[student_name == 'Jack', :1]
# array([[83]])

array([[83]])

In [66]:
# 数组的转置和轴对称
arr = np.arange(12).reshape(3,4)
arr
# array([[ 0,  1,  2,  3],
#       [ 4,  5,  6,  7],
#       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
arr.T
# array([[ 0,  4,  8],
#       [ 1,  5,  9],
#       [ 2,  6, 10],
#       [ 3,  7, 11]])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
arr = np.arange(16).reshape((2,2,4))
arr
# array([[[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7]],
#
#       [[ 8,  9, 10, 11],
#        [12, 13, 14, 15]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.transpose(1,2,0)
# array([[[ 0,  8],
#        [ 1,  9],
#        [ 2, 10],
#        [ 3, 11]],
#
#       [[ 4, 12],
#        [ 5, 13],
#        [ 6, 14],
#        [ 7, 15]]])

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [70]:
arr.swapaxes(1,0)
# array([[[ 0,  1,  2,  3],
#        [ 8,  9, 10, 11]],
#
#       [[ 4,  5,  6,  7],
#        [12, 13, 14, 15]]])

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [71]:
# NumPy通用函数
arr = np.array([4,9,16])
np.sqrt(arr)  # array([2., 3., 4.])

array([2., 3., 4.])

In [72]:
np.abs(arr)  # array([ 4,  9, 16])

array([ 4,  9, 16])

In [73]:
np.square(arr)  # array([ 16,  81, 256], dtype=int32)

array([ 16,  81, 256], dtype=int32)

In [74]:
x = np.array([12,9,13,15])
y = np.array([11,10,4,8])
np.add(x,y)  # array([23, 19, 17, 23])

array([23, 19, 17, 23])

In [75]:
np.multiply(x,y)  # array([132,  90,  52, 120])

array([132,  90,  52, 120])

In [77]:
np.maximum(x, y)  # array([12, 10, 13, 15])

array([12, 10, 13, 15])

In [78]:
np.greater(x, y)  # array([ True, False,  True,  True])

array([ True, False,  True,  True])

In [79]:
# 利用NumPy数组进行数据处理
# 将条件逻辑转为数组运算
arr_x = np.array([1,5,7])
arr_y = np.array([2,6,8])
arr_con = np.array([True,False,True])
result = np.where(arr_con, arr_x, arr_y)
result  # array([1, 6, 7])

array([1, 6, 7])

In [ ]:
# 数组统计运算

In [80]:
arr = np.arange(10)
arr.sum()  # 45

45

In [81]:
arr.mean()  # 4.5

4.5

In [82]:
arr.min()  # 0

0

In [83]:
arr.max()  # 9

9

In [84]:
arr.argmax() # 9  求最大值的索引

9

In [85]:
arr.argmin()  # 0 求最小值的索引

0

In [86]:
arr.cumsum()  # 计算元素的累计和
# array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [87]:
arr.cumprod()  # 计算元素的累计积
# array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [88]:
x = np.arange(1,16).reshape((3,5))
print(x)
# [[ 1  2  3  4  5]
# [ 6  7  8  9 10]
# [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [89]:
np.diff(x, axis=1) # 默认axis=1，代表x轴方向
# array([[1, 1, 1, 1],
#       [1, 1, 1, 1],
#       [1, 1, 1, 1]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [90]:
np.diff(x, axis=0) # 0代表 y轴方向
# array([[5, 5, 5, 5, 5],
#       [5, 5, 5, 5, 5]])

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [91]:
np.floor([-0.6, -1.4, -0.1, -1.8, 0, 1.4, 1.7])
# array([-1., -2., -1., -2.,  0.,  1.,  1.])

array([-1., -2., -1., -2.,  0.,  1.,  1.])

In [92]:
np.ceil([1.2, 1.5, 1.8, 2.1, 2.0, -0.5, -0.6, -0.3])
# array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])

array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])

In [93]:
x = np.array([[1,0],[2,-2],[-2,1]])
np.where(x>0, x, 0)  # 大于0的不便，小于0 的用0取代
# array([[1, 0],
#       [2, 0],
#       [0, 1]])

array([[1, 0],
       [2, 0],
       [0, 1]])

In [95]:
# 数组排序
arr = np.array([[6,2,7],[3,6,2],[4,3,2]])
arr.sort()
arr
# array([[2, 6, 7],
#       [2, 3, 6],
#       [2, 3, 4]])

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [96]:
arr = np.array([[6,2,7],[3,6,2],[4,3,2]])
arr.sort(0)  # 沿着编号为0的轴对元素排序 （相当于是y轴）
arr
# array([[3, 2, 2],
#       [4, 3, 2],
#       [6, 6, 7]])

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

In [114]:
# numpy.diff(a, n=1, axis=1)
# 沿着指定轴计算第N维的离散差值
# 参数：
#     a: 输入矩阵
#     n: 可选，代表要执行几次差值
#     axis: 默认是1,沿x轴最后一个，0代表沿y轴最后一个
arr = np.arange(2,14).reshape((3,4))
arr
# array([[ 2,  3,  4,  5],
#       [ 6,  7,  8,  9],
#       [10, 11, 12, 13]])
np.diff(arr)  # 最后一个元素 - 前一个元素
# array([[1, 1, 1],
#       [1, 1, 1],
#       [1, 1, 1]])
np.diff(arr,axis=1)
#array([[1, 1, 1],
#       [1, 1, 1],
#       [1, 1, 1]])
np.diff(arr, axis=0)
# array([[4, 4, 4, 4],
#       [4, 4, 4, 4]])

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [116]:
# 检索数组元素
arr = np.array([[1,-2,-7],[-3,6,2],[-4,3,2]])
np.any(arr > 0) # arr中所有元素是否有一个大于0
# True
np.all(arr > 0) # arr中所有元素是否都大于0
# False

False

In [119]:
# 唯一化及其他集合逻辑
arr = np.array([12,11,12,11,23,34,8])
np.unique(arr)
# array([ 8, 11, 12, 23, 34])
np.in1d(arr, [11,12])
# array([ True,  True,  True,  True, False, False, False])

array([ True,  True,  True,  True, False, False, False])

In [120]:
# 线性代数模块
arr_x = np.array([[1,2,3],[4,5,6]])
arr_y = np.array([[1,2],[3,4],[5,6]])
arr_x.dot(arr_y) # 等价于np.dot(arr_x, arr_y)
# array([[22, 28],
#       [49, 64]])

array([[22, 28],
       [49, 64]])

In [125]:
# 随机数模块
np.random.rand(3,3) # 生成一个二维数组
# array([[0.65681616, 0.87434912, 0.58502301],
#       [0.03523995, 0.76161422, 0.23286451],
#       [0.90213581, 0.28687796, 0.58325295]])
np.random.rand(2,3,3) # 随机生成一个三维数组
# array([[[0.37724397, 0.64220175, 0.91837001],
#        [0.7730453 , 0.85312294, 0.35899016],
#        [0.26583544, 0.954334  , 0.01339393]],
#
#       [[0.51987373, 0.35655088, 0.47461904],
#        [0.84228396, 0.24641636, 0.04072919],
#        [0.42446348, 0.36755701, 0.44920097]]])
np.random.seed(0) # 生成随机数种子
np.random.rand(5) # 随机生成包含5个元素的浮点数组
# array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])
np.random.seed(0)
np.random.rand(5)
# array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])
np.random.seed()
np.random.rand(5)
# array([0.07027274, 0.17125665, 0.97820993, 0.99702874, 0.37412418])

array([0.07027274, 0.17125665, 0.97820993, 0.99702874, 0.37412418])