# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.20.3'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/TJH/devEnv/anaconda3\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.empty(10)

array([2.12199579e-314, 0.00000000e+000, 2.12199579e-314, 4.94065646e-324,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
arr = np.arange(10).reshape((2,5))
arr
# array([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9]])
arr.size
# 10
arr.itemsize
# 4
print('%d bytes'%(arr.size * arr.itemsize))
# 40 bytes

40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.info(np.add)
# add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

# Add arguments element-wise.

# Parameters
# ----------
# x1, x2 : array_like
#     The arrays to be added.
#     If ``x1.shape != x2.shape``, they must be broadcastable to a common
#     shape (which becomes the shape of the output).
# out : ndarray, None, or tuple of ndarray and None, optional
#     A location into which the result is stored. If provided, it must have
#     a shape that the inputs broadcast to. If not provided or None,
#     a freshly-allocated array is returned. A tuple (possible only as a
#     keyword argument) must have length equal to the number of outputs.
# where : array_like, optional
#     This condition is broadcast over the input. At locations where the
#     condition is True, the `out` array will be set to the ufunc result.
#     Elsewhere, the `out` array will retain its original value.
#     Note that if an uninitialized `out` array is created via the default
#     ``out=None``, locations within it where the condition is False will
#     remain uninitialized.
# **kwargs
#     For other keyword-only arguments, see the
#     :ref:`ufunc docs <ufuncs.kwargs>`.

# Returns
# -------
# add : ndarray or scalar
#     The sum of `x1` and `x2`, element-wise.
#     This is a scalar if both `x1` and `x2` are scalars.

# Notes
# -----
# Equivalent to `x1` + `x2` in terms of array broadcasting.

# Examples
# --------
# >>> np.add(1.0, 4.0)
# 5.0
# >>> x1 = np.arange(9.0).reshape((3, 3))
# >>> x2 = np.arange(3.0)
# >>> np.add(x1, x2)
# array([[  0.,   2.,   4.],
#        [  3.,   5.,   7.],
#        [  6.,   8.,  10.]])

# The ``+`` operator can be used as a shorthand for ``np.add`` on ndarrays.

# >>> x1 = np.arange(9.0).reshape((3, 3))
# >>> x2 = np.arange(3.0)
# >>> x1 + x2
# array([[ 0.,  2.,  4.],
#        [ 3.,  5.,  7.],
#        [ 6.,  8., 10.]])
%run python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Exception: File `'python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr = np.zeros(10)
arr[4] = 1
print(arr)
# [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
arr = np.arange(1,10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
arr = np.array([1,2,0,0,4,0])
arr.nonzero()
arr[arr.nonzero()]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
np.random.random((3,3,3))
np.random.rand(3,3,3)

array([[[0.65694076, 0.53557329, 0.14517006],
        [0.33764604, 0.41077491, 0.20982871],
        [0.76948611, 0.92891904, 0.70220561]],

       [[0.69891825, 0.19952774, 0.31438444],
        [0.01273508, 0.99057268, 0.03251633],
        [0.82552564, 0.49130177, 0.06302327]],

       [[0.21239842, 0.30869745, 0.65556636],
        [0.17065289, 0.81190213, 0.07100002],
        [0.20103121, 0.63836553, 0.5217681 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
np.random.seed(0)
arr = np.random.rand(10,10)
amax, amin = arr.max(),arr.min()
print(amax, amin)

0.9883738380592262 0.004695476192547066


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
arr = np.random.random(30)
arr.mean()

0.5469142718444804

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [50]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [61]:
arr = np.ones((5,5))
arr[[0,-1],:]=0
arr[:,[0,-1]] = 0

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [70]:
# NaN = not a number, inf = infinity`
0 * np.nan  # nan
np.nan == np.nan # False
np.inf > np.nan  # False
np.nan - np.nan  # nan
np.nan in set([np.nan]) # True
3*0.1  # 0.30000000000000004
0.3 == 3*0.1  # False

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [83]:
Z = np.diag(1+np.arange(4),k=-1)

np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [89]:
arr = np.zeros((8,8), dtype=int)
arr[::2,::2] = 1
arr[1::2, 1::2] = 1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [90]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [91]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [92]:
np.random.seed(0)
arr = np.random.random((5,5))
z = (arr - np.mean(arr))/ np.std(arr)
z

array([[-0.14854421,  0.44055117,  0.04247881, -0.1624605 , -0.59169993],
       [ 0.19519398, -0.54236874,  1.06578972,  1.32033341, -0.73408512],
       [ 0.71154487, -0.21907095, -0.08045184,  1.18555078, -1.84023484],
       [-1.78325269, -2.02016749,  0.85634317,  0.66350295,  0.98873998],
       [ 1.37328739,  0.73786513, -0.4577726 ,  0.67190312, -1.67297558]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [94]:

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [112]:
arr = np.arange(11)
np.any(arr > 3)
np.all(arr > 5)

arr[(arr > 3) & (arr < 8)] *= (-1)
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [113]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [122]:
np.array(0)  # array(0)
np.array(0) / np.array(0)  # nan
np.array(0) // np.array(0)  # 0
np.array([np.nan]).astype(int).astype(float)

C:\Users\HOLIDA~1.YAN\AppData\Local\Temp/ipykernel_27844/2508843615.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)  # nan
C:\Users\HOLIDA~1.YAN\AppData\Local\Temp/ipykernel_27844/2508843615.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)  # 0


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [123]:
Z = np.random.uniform(-10,+10,10)
Z


array([ 2.79842043, -7.13293425,  8.89337834,  0.43696644, -1.7067612 ,
       -4.70888776,  5.48467379, -0.87699336,  1.36867898, -9.62420399])

In [125]:
arr = np.abs(Z)
np.ceil(arr)
#print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
#print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

array([ 3.,  8.,  9.,  1.,  2.,  5.,  6.,  1.,  2., 10.])

In [126]:
np.copysign(np.ceil(arr), Z)

array([  3.,  -8.,   9.,   1.,  -2.,  -5.,   6.,  -1.,   2., -10.])

In [127]:
np.where(Z>0, np.ceil(Z), np.floor(Z))

array([  3.,  -8.,   9.,   1.,  -2.,  -5.,   6.,  -1.,   2., -10.])

#### 30. How to find common values between two arrays? (★☆☆)

In [138]:
np.random.seed(0)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1,Z2
np.intersect1d(Z1,Z2)  # 注意这个是1234 的 1

array([7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [142]:
'''
python
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
'''
defaults = np.seterr(all="ignore")
Z = np.ones(1)  / 0
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [145]:
np.sqrt(-1) == np.emath.sqrt(-1)  # NaN == 1j
# False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [148]:
'''
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
'''
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2022-01-26'),
 numpy.datetime64('2022-01-27'),
 numpy.datetime64('2022-01-28'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [149]:
'''
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
'''
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [153]:
'''
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
'''
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)